import type { LucideIcon } from "lucide-react";
import {
  BellRing,
  Bug,
  Database,
  DollarSign,
  FileOutput,
  Languages,
  LifeBuoy,
  Mail,
  MapPinned,
  Scale,
  Shield,
  SlidersHorizontal,
  SunMoon,
  Trash2,
  Users,
} from "lucide-react";
import type { IntroStep } from "@/lib/onboarding/content";

export const OPERATOR_INTRO_VERSION = "v3";
export const OPERATOR_INTRO_STORAGE_KEY = `octivate-operator-intro-${OPERATOR_INTRO_VERSION}`;
export const OPERATOR_INTRO_EVENT = "octivate:open-operator-intro";

/** Brief tour of operator console tabs — hash routes stay on /dashboard/operator. */
export const OPERATOR_INTRO_STEPS: IntroStep[] = [
  {
    id: "pulse",
    kicker: "Step 1 · Pulse",
    title: "Start on",
    titleAccent: "Pulse",
    tagline: "Live health of the production pipeline.",
    description:
      "Pulse is the operator home. Scan session health, token burn, and review queues before diving into deeper controls.",
    bullets: [
      { lead: "KPIs", text: "show tokens, agents, and review load" },
      { lead: "Hash tabs", text: "jump any console section instantly" },
    ],
    icon: Shield,
    art: "overview",
    accent: "violet",
    route: "/dashboard/operator#pulse",
    target: "[data-tour='op-tab-pulse']",
    demo: "highlight",
    requireSidebar: true,
  },
  {
    id: "coverage",
    kicker: "Step 2 · Theatre coverage",
    title: "Workspace ships a",
    titleAccent: "Theatre coverage map",
    tagline: "Indicate only — stays on the operator console.",
    description:
      "Members see a live Theatre coverage map on Workspace Overview (Leaflet hotspots by country). Operators keep working here; open Workspace mode when you want to inspect the map itself. This step only indicates the addition.",
    bullets: [
      { lead: "Overview map", text: "lives on /dashboard for members" },
      { lead: "Hotspots", text: "reflect project geography and counts" },
      { lead: "No redirect", text: "this tour stays on the operator console" },
    ],
    icon: MapPinned,
    art: "map",
    accent: "teal",
    route: "/dashboard/operator#pulse",
    target: "[data-tour='op-tab-pulse']",
    demo: "highlight",
    requireSidebar: true,
  },
  {
    id: "operations",
    kicker: "Step 3 · Operations",
    title: "Clear and",
    titleAccent: "moderate",
    tagline: "Session cleanup, i18n sync, and logbook publish.",
    description:
      "Operations covers maintenance — pruning stuck sessions, moderation queues, i18n catalog sync, and the Future Caribbean Logbook publisher.",
    bullets: [
      { lead: "Use sparingly", text: "actions here affect live production state" },
      { lead: "Audit", text: "events land in Debug for forensics" },
    ],
    icon: Trash2,
    art: "pipeline",
    accent: "amber",
    route: "/dashboard/operator#operations",
    target: "[data-tour='op-tab-operations']",
    demo: "highlight",
    requireSidebar: true,
  },
  {
    id: "control",
    kicker: "Step 4 · Control",
    title: "Tune platform",
    titleAccent: "limits",
    tagline: "Tokens, uploads, avatars, and review policy.",
    description:
      "Control sets runtime caps: daily tokens, concurrent agents, upload size, avatar KB, bio length, and human-review policy. Changes autosave.",
    bullets: [
      { lead: "Account profile", text: "avatar KB + bio chars for members" },
      { lead: "Policy toggles", text: "premium models and required review" },
    ],
    icon: SlidersHorizontal,
    art: "projects",
    accent: "teal",
    route: "/dashboard/operator#control",
    target: "[data-tour='op-tab-control']",
    demo: "highlight",
    requireSidebar: true,
  },
  {
    id: "catalog",
    kicker: "Step 5 · Catalog",
    title: "Sources and",
    titleAccent: "signals",
    tagline: "Import and curate evidence inputs.",
    description:
      "Catalog manages source packs and imports that feed monitors and doctrine runs. Keep provenance clean before briefs ship.",
    bullets: [
      { lead: "Import", text: "adds curated regional sources" },
      { lead: "Quality in", text: "quality out for downstream briefs" },
    ],
    icon: Database,
    art: "monitors",
    accent: "teal",
    route: "/dashboard/operator#catalog",
    target: "[data-tour='op-tab-catalog']",
    demo: "highlight",
    requireSidebar: true,
  },
  {
    id: "support",
    kicker: "Step 6 · Customer Support",
    title: "Staff",
    titleAccent: "Customer Support",
    tagline: "Live customer threads with safe previews.",
    description:
      "Customer Support is the founder inbox. Reply in-thread, preview attachments in-browser, and never download untrusted files locally. Members use Help chat; you answer here.",
    bullets: [
      { lead: "Live stream", text: "keeps threads current under load" },
      { lead: "Avatars", text: "identify Shemuel and Jaden" },
    ],
    icon: LifeBuoy,
    art: "support",
    accent: "violet",
    route: "/dashboard/operator#support",
    target: "[data-tour='op-tab-support']",
    demo: "highlight",
    requireSidebar: true,
  },
  {
    id: "support-alerts",
    kicker: "Step 7 · Support alerts",
    title: "Never miss a",
    titleAccent: "member reply",
    tagline: "Background alerts stay armed across console tabs.",
    description:
      "Operator support alerts listen in the background. New member messages push toasts and deep-link into the Customer Support thread — even when you are on Pulse or Mail.",
    bullets: [
      { lead: "Toasts", text: "surface new member messages immediately" },
      { lead: "Open thread", text: "jumps into Customer Support for that account" },
      { lead: "Always on", text: "SSE stays armed while you are signed in as operator" },
    ],
    icon: BellRing,
    art: "support",
    accent: "amber",
    route: "/dashboard/operator#support",
    target: "[data-tour='op-tab-support']",
    demo: "pulse",
    requireSidebar: true,
  },
  {
    id: "translate",
    kicker: "Step 8 · Translation",
    title: "Operator",
    titleAccent: "language control",
    tagline: "Same realtime catalogs as the public site.",
    description:
      "Locale catalogs power member chrome and legal copy. Preview languages from the public site language control; sync full catalogs from Operations.",
    bullets: [
      { lead: "Public chrome", text: "hosts the language picker on marketing pages" },
      { lead: "Catalogs", text: "match what members and landing visitors see" },
      { lead: "Operations", text: "hosts full catalog sync tooling" },
    ],
    icon: Languages,
    art: "translate",
    accent: "violet",
    route: "/dashboard/operator#pulse",
    demo: "highlight",
  },
  {
    id: "lighting",
    kicker: "Step 9 · Lighting",
    title: "Set console",
    titleAccent: "lighting",
    tagline: "Light or dark for long operator sessions.",
    description:
      "Lighting switches light and dark themes for the operator console and workspace. Use the sun / moon control on the public site navbar or footer.",
    bullets: [
      { lead: "Toggle", text: "lives on marketing chrome, not the operator sidebar" },
      { lead: "Shared", text: "theme preference follows you into Workspace mode" },
      { lead: "Accessibility", text: "use whichever lighting reduces eye strain" },
    ],
    icon: SunMoon,
    art: "theme",
    accent: "amber",
    route: "/dashboard/operator#pulse",
    demo: "highlight",
  },
  {
    id: "mail",
    kicker: "Step 10 · Mail",
    title: "Send from your",
    titleAccent: "account",
    tagline: "Mailing list + Haraka outbound.",
    description:
      "Mail composes to subscribers with the default HTML template. Your signed-in address is the preferred From; list recipients come from the landing mailing list.",
    bullets: [
      { lead: "From", text: "defaults to your operator email" },
      { lead: "Debug", text: "captures Haraka warnings and errors" },
    ],
    icon: Mail,
    art: "briefs",
    accent: "amber",
    route: "/dashboard/operator#mail",
    target: "[data-tour='op-tab-mail']",
    demo: "highlight",
    requireSidebar: true,
  },
  {
    id: "users",
    kicker: "Step 11 · Users",
    title: "See members",
    titleAccent: "and bios",
    tagline: "Counts, disable, and password resets.",
    description:
      "Users shows registration mix, mailing activity, avatars, and descriptions. Founder operators stay protected from disable/reset here.",
    bullets: [
      { lead: "Reset password", text: "copies a one-time secret" },
      { lead: "Founders", text: "cannot be moderated in this panel" },
    ],
    icon: Users,
    art: "overview",
    accent: "teal",
    route: "/dashboard/operator#users",
    target: "[data-tour='op-tab-users']",
    demo: "highlight",
    requireSidebar: true,
  },
  {
    id: "pricing",
    kicker: "Step 12 · Pricing",
    title: "Edit plan",
    titleAccent: "copy",
    tagline: "Public pricing cards and notes.",
    description:
      "Pricing updates the live plans shown on the marketing site. Keep amounts and feature notes accurate before publishing.",
    bullets: [
      { lead: "Autosave", text: "writes to billing plans storage" },
      { lead: "Public page", text: "reads the same source of truth" },
    ],
    icon: DollarSign,
    art: "projects",
    accent: "violet",
    route: "/dashboard/operator#pricing",
    target: "[data-tour='op-tab-pricing']",
    demo: "highlight",
    requireSidebar: true,
  },
  {
    id: "exports",
    kicker: "Step 13 · Exports",
    title: "Shape brief",
    titleAccent: "templates",
    tagline: "HTML export layouts for stakeholders.",
    description:
      "Exports lets you design, preview, and upload HTML templates used when briefs leave the platform as packs.",
    bullets: [
      { lead: "Preview", text: "renders against a sample brief" },
      { lead: "Upload", text: "accepts styled HTML packages" },
    ],
    icon: FileOutput,
    art: "briefs",
    accent: "amber",
    route: "/dashboard/operator#exports",
    target: "[data-tour='op-tab-exports']",
    demo: "highlight",
    requireSidebar: true,
  },
  {
    id: "legal",
    kicker: "Step 14 · Legal",
    title: "Privacy Policy",
    titleAccent: "& Terms of Service",
    tagline: "Open either page from the sidebar footer.",
    description:
      "Members accept Privacy Policy and Terms of Service at signup. Operators can open either public page from the sidebar footer links anytime.",
    bullets: [
      { lead: "Privacy Policy", text: "is published for public trust" },
      { lead: "Terms of Service", text: "govern accounts and platform use" },
      { lead: "Sidebar footer", text: "links navigate to the full legal pages" },
    ],
    icon: Scale,
    art: "legal",
    accent: "teal",
    route: "/dashboard/operator#pulse",
    target: "[data-tour='legal-notice']",
    demo: "highlight",
    requireSidebar: true,
  },
  {
    id: "debug",
    kicker: "Step 15 · Debug",
    title: "Watch the",
    titleAccent: "live console",
    tagline: "OpenRouter, pipeline, mail, and security events.",
    description:
      "Debug streams ops events. Filter by Mail when testing SMTP, or Security after password/avatar changes. Clear only when you mean it.",
    bullets: [
      { lead: "Mail source", text: "shows Haraka warn/error payloads" },
      { lead: "Replay", text: "this tour anytime from Operator Tutorial" },
    ],
    icon: Bug,
    art: "pipeline",
    accent: "violet",
    route: "/dashboard/operator#debug",
    target: "[data-tour='op-tab-debug']",
    demo: "pulse",
    requireSidebar: true,
  },
];

export type { LucideIcon };
