/** Compact ISO-style country list for merchant checkout. */
export const BILLING_COUNTRIES: { code: string; name: string }[] = [
  { code: "AG", name: "Antigua and Barbuda" },
  { code: "BB", name: "Barbados" },
  { code: "BZ", name: "Belize" },
  { code: "BM", name: "Bermuda" },
  { code: "BQ", name: "Bonaire, Sint Eustatius and Saba" },
  { code: "CA", name: "Canada" },
  { code: "KY", name: "Cayman Islands" },
  { code: "CU", name: "Cuba" },
  { code: "CW", name: "Curaçao" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic" },
  { code: "GD", name: "Grenada" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" },
  { code: "JM", name: "Jamaica" },
  { code: "MQ", name: "Martinique" },
  { code: "MS", name: "Montserrat" },
  { code: "PR", name: "Puerto Rico" },
  { code: "KN", name: "Saint Kitts and Nevis" },
  { code: "LC", name: "Saint Lucia" },
  { code: "VC", name: "Saint Vincent and the Grenadines" },
  { code: "SR", name: "Suriname" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "TC", name: "Turks and Caicos Islands" },
  { code: "GB", name: "United Kingdom" },
  { code: "US", name: "United States" },
  { code: "VG", name: "British Virgin Islands" },
  { code: "VI", name: "U.S. Virgin Islands" },
  { code: "AW", name: "Aruba" },
  { code: "BS", name: "Bahamas" },
  { code: "FR", name: "France" },
  { code: "NL", name: "Netherlands" },
  { code: "DE", name: "Germany" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "SG", name: "Singapore" },
  { code: "AU", name: "Australia" },
  { code: "NZ", name: "New Zealand" },
  { code: "IN", name: "India" },
  { code: "NG", name: "Nigeria" },
  { code: "ZA", name: "South Africa" },
  { code: "BR", name: "Brazil" },
  { code: "MX", name: "Mexico" },
  { code: "OTHER", name: "Other" },
];
